#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 3
final_space = true
#console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
type = 'path'
style = 'plain'
foreground = 'blue'
background = 'transparent'
template = '{{ .Path }}'

[blocks.segments.properties]
style = 'full'

[[blocks.segments]]
type = 'git'
style = 'plain'
foreground = 'p:grey'
background = 'transparent'
template = '{{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}* {{ end }}<cyan>{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}</>'

[blocks.segments.properties]
branch_icon = '  '
commit_icon = ' @'
fetch_status = true

[[blocks]]
type = 'rprompt'
overflow = 'hidden'

[[blocks.segments]]
type = 'executiontime'
style = 'plain'
foreground = 'yellow'
background = 'transparent'
template = '{{ .FormattedMs }}'

[blocks.segments.properties]
threshold = 5000

[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
type = 'text'
style = 'plain'
foreground = 'cyan'
background = 'transparent'
template = '{{ .UserName }}'

[[blocks.segments]]
type = 'text'
style = 'plain'
foreground = 'green'
background = 'transparent'
template = '@'

[[blocks.segments]]
type = 'text'
style = 'plain'
foreground = 'cyan'
background = 'transparent'
template = '{{ .HostName }}'


[[blocks.segments]]
type = 'shell'
style = 'plain'
foreground_templates = [
	'{{ if gt .Code 0 }}red{{ end }}',
	'{{ if eq .Code 0 }}magenta{{ end }}',
]
background = 'transparent'
template = ' '

[transient_prompt]
template = ' '
background = 'transparent'
foreground_templates = [
	'{{if gt .Code 0}}red{{end}}',
	'{{if eq .Code 0}}magenta{{end}}',
]

[secondary_prompt]
template = ' '
foreground = 'magenta'
background = 'transparent'

[[blocks]]
type = 'add'
alignment = 'right'
newline = true
